# Generated by Django 2.2.4 on 2021-01-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DstagramApp', '0002_auto_20210123_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
