# Generated by Django 2.2.4 on 2021-01-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DstagramApp', '0003_auto_20210124_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
