# Generated by Django 2.2.4 on 2021-02-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DstagramApp', '0004_auto_20210125_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DstagramApp.User')),
                ('photoCommented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DstagramApp.Photo')),
            ],
        ),
    ]
