# Generated by Django 2.2.4 on 2021-02-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DstagramApp', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Commenter',
            new_name='commenter',
        ),
    ]
